### ISSUE TITLE
お風呂の蓋を買う

### ISSUE THREAD

**Issue by t-kashima** [t-kashima/home#13]
## 概要

- お風呂の蓋がないとすぐに温度が下がってしまうので蓋を買う

## ToDo

- [x] お風呂の蓋を購入する

**Comment by t-kashima** [comment]
ふたはまずどこで売っているのか謎... ニトリかホームセンターかな...

**Comment by hiromichi-takeo** [comment]
Amazonが豊富
http://www.amazon.co.jp/%E6%9D%B1%E3%83%97%E3%83%AC-%E6%8A%97%E8%8F%8C%E3%82%BF%E3%82%A4%E3%83%97-%E6%8A%98%E3%82%8A%E3%81%9F%E3%81%9F%E3%81%BF%E5%BC%8F%E9%A2%A8%E5%91%82%E3%81%B5%E3%81%9F-70%C3%97109cm-%E3%83%A1%E3%82%BF%E3%83%AA%E3%83%83%E3%82%AF%E3%82%B0%E3%83%AC%E3%83%BC/dp/B001GTU1IA/ref=lp_334619011_1_2?s=home&ie=UTF8&qid=1453694322&sr=1-2

**Comment by t-kashima** [comment]
お風呂の蓋のベストセラー！たしかに。Amazonにしよう！！！

**Comment by t-kashima** [comment]
竹尾さんが貼ってくれているお風呂の蓋を購入しました！

**Comment by t-kashima** [comment]
こちら届きました！！
