### ISSUE TITLE
定期券を買う

### ISSUE THREAD

**Issue by t-kashima** [t-kashima/home#15]
光が丘〜青山一丁目、青山一丁目〜渋谷の定期券を買う

**Comment by t-kashima** [comment]
青山一丁目〜渋谷区間、銀座線だけだと思ったら半蔵門線も同じ定期でいけるとのこと。
http://www.tokyometro.jp/ticket/types/pass/commuter/

**Comment by t-kashima** [comment]
だいたいの定期券売り場は7:40〜20:00までなので注意したい

**Comment by t-kashima** [comment]
券売機だとだいたい始発〜終電まで売ってる

**Comment by tamai** [comment]
定期券分割しなくても買えませんか？

**Comment by t-kashima** [comment]
@tamai ありがとうございます！その通りで、
分割で買うとだめですって言われたので、一度払い戻しをして
20時までに定期券売り場で買います！！

**Comment by t-kashima** [comment]
渋谷の定期券売り場でまとめて買おう

**Comment by t-kashima** [comment]
渋谷では買えなくて、練馬の定期券売り場で払い戻しして光が丘〜渋谷で買いました！
