### ISSUE TITLE
家の傷を確認する

### ISSUE THREAD

**Issue by t-kashima** [t-kashima/home#4]
## 概要

- 家の傷がないかを確認して管理会社へ送る

## ToDo

- [x] 家の傷を確認する
- [x] 管理会社へ郵送する

**Comment by koogawa** [comment]
うちも入居時に傷を確認して、写真（日付入り）で残しておきました！

**Comment by t-kashima** [comment]
なるほど。写真という手が！
出ていく時にこれ始めからありましたっていうの若干信じてもらえそうにないのでたしかに！！

**Comment by t-kashima** [comment]
これ今週末までに確認して配送する

**Comment by t-kashima** [comment]
傷を確認してFAXで送りました！

**Comment by koogawa** [comment]
おつかれさまです！
